edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
fn_args_layout = "Tall"
brace_style = "SameLineWhere"
warn_on_all_formatible_found = false
format_strings = false
format_macro_matchers = true
format_macro_bodies = true
hex_literal_case = "Lower"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
use_try_shorthand = true
use_field_init_shorthand = true
force_explicit_abi = true
normalize_comments = true
wrap_comments = true
comment_width = 80